import { SPECIES_MEDIA_WAVE } from '../data/marketCatalogSpeciesMediaWave'
import { getOffersByWorld } from '../data/marketCatalog'
import { AGRONEXUS_COMMERCE } from '../data/commerceConfig'

const money=(v)=>v==null?null:new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v)
const norm=(v='')=>String(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')

export default function AgroNexusSpeciesPage({speciesKey}){
 const key=norm(speciesKey)
 const species=SPECIES_MEDIA_WAVE.find(x=>norm(x.slug)===key||String(x.id)===speciesKey)
 if(!species)return <main style={{padding:'180px 7vw',minHeight:'100vh'}}><h1>Espécie não encontrada.</h1><a href="#/aves">Voltar para Aves</a></main>
 const offers=getOffersByWorld('aves').filter(x=>norm(x.name).includes(norm(species.name))||norm(species.name).includes(norm(x.name)))
 const offer=offers[0]
 const price=offer?.price??offer?.salePrice??null
 return <main className="species-page"><style>{`.species-page{background:#f1efe7;color:#101411;min-height:100vh;padding-top:92px}.sp-hero{display:grid;grid-template-columns:1.05fr .95fr;min-height:72vh;background:#07110d;color:#fff}.sp-media{min-height:560px;background:#152019}.sp-media img{width:100%;height:100%;object-fit:cover;display:block}.sp-copy{padding:clamp(50px,7vw,110px);display:flex;flex-direction:column;justify-content:center}.sp-k{color:#9ee5b3;font:900 .65rem Inter;letter-spacing:.16em;text-transform:uppercase}.sp-copy h1{font:650 clamp(3.7rem,7vw,7.5rem)/.86 'Space Grotesk',Inter;letter-spacing:-.065em;margin:18px 0}.sp-copy p{max-width:650px;color:rgba(255,255,255,.7);line-height:1.7}.sp-price{font:800 clamp(1.8rem,3vw,3rem) Inter;margin:25px 0}.sp-actions{display:flex;gap:8px;flex-wrap:wrap}.sp-actions a{padding:15px 20px;background:#9ee5b3;color:#07110d;text-decoration:none;font:900 .65rem Inter;letter-spacing:.08em;text-transform:uppercase}.sp-info{padding:70px 7vw 100px}.sp-info h2{font:650 clamp(2.5rem,5vw,5rem)/.9 'Space Grotesk';letter-spacing:-.05em}.sp-grid{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid #ccc}.sp-grid div{padding:25px;border-right:1px solid #ccc}.sp-grid strong{display:block;margin-bottom:8px}@media(max-width:760px){.sp-hero{grid-template-columns:1fr}.sp-media{min-height:55vh}.sp-grid{grid-template-columns:1fr}.sp-grid div{border-right:0;border-bottom:1px solid #ccc}}`}</style><section className="sp-hero"><div className="sp-media"><img src={species.image} alt={species.name}/></div><div className="sp-copy"><div className="sp-k">AgroNexus™ · Aves</div><h1>{species.name}</h1><p>{offer?.description||species.description||`Conheça ${species.name} na AgroNexus™.`}</p>{price!=null?<div className="sp-price">{money(price)}</div>:<div className="sp-price">Consulte disponibilidade</div>}<div className="sp-actions"><a href={AGRONEXUS_COMMERCE.contactLinks.whatsapp.url} target="_blank" rel="noreferrer">Consultar no WhatsApp</a><a href="#/aves">Voltar para Aves</a></div></div></section><section className="sp-info"><h2>Informações.</h2><div className="sp-grid"><div><strong>Espécie</strong>{species.name}</div><div><strong>Grupo</strong>{species.categories?.filter(x=>x!=='aves'&&x!=='psitacideos').join(' · ')||'Psitacídeos'}</div><div><strong>Disponibilidade</strong>{offer?.stockLabel||'Consulte a AgroNexus™'}</div></div></section></main>
}