import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { AGRONEXUS_COMMERCE } from '../data/commerceConfig'

const ESPECIES={jabuticaba:{nome:'Jabuticaba',x:6,y:6,preco:45},citros:{nome:'Citros',x:7,y:5,preco:35},goiaba:{nome:'Goiaba',x:6,y:5,preco:30},manga:{nome:'Manga',x:10,y:10,preco:40},abacate:{nome:'Abacate',x:10,y:10,preco:45},maracuja:{nome:'Maracujá',x:4,y:2,preco:25,tutor:true},uva:{nome:'Uva',x:2.5,y:1.5,preco:30,tutor:true},banana:{nome:'Banana',x:4,y:3,preco:20},nativas:{nome:'Nativas',x:3,y:2,preco:15}}
const num=(v,d)=>Math.max(.1,Number(v)||d)
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0})

export default function AgroNexusPomarCalculator(){
 const [tipo,setTipo]=useState('jabuticaba'); const [comp,setComp]=useState(20); const [larg,setLarg]=useState(10)
 const r=useMemo(()=>{const e=ESPECIES[tipo],area=num(comp,20)*num(larg,10),util=area*.85,mudas=Math.max(1,Math.floor(util/(e.x*e.y))); return {e,area,util,mudas,organico:mudas*12,npk:mudas*.15,tutores:e.tutor?mudas:0,invest:mudas*e.preco}},[tipo,comp,larg])
 const msg=`Olá! Quero montar meu pedido de pomar. Espécie: ${r.e.nome}. Área: ${r.area.toFixed(0)} m² (${r.util.toFixed(0)} m² úteis). Espaçamento: ${r.e.x} x ${r.e.y} m. Mudas: ${r.mudas}.${r.tutores?` Tutores: ${r.tutores}.`:''} Adubo orgânico: ${r.organico} kg. NPK inicial: ${r.npk.toFixed(1)} kg. Investimento estimado em mudas: ${brl(r.invest)}.`
 const wa=`${AGRONEXUS_COMMERCE.contactLinks.whatsapp.url}?text=${encodeURIComponent(msg)}`
 return <main className="pom"><style>{`.pom{min-height:100vh;background:#fffaf2;padding:118px 20px 80px;font-family:Inter,system-ui,sans-serif;color:#101828}.pom__w{max-width:980px;margin:auto}.pom h1{font-size:clamp(2rem,5vw,3.5rem);margin:0 0 8px}.pom p{color:#475467}.pom__grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0}.pom label{background:#fff;border:1px solid #e4cfa5;border-radius:12px;padding:12px;font-weight:800;font-size:.78rem}.pom input,.pom select{width:100%;margin-top:7px;padding:11px;border:1px solid #bda778;border-radius:8px}.pom__result{background:#fff;border:1px solid #fdb022;border-radius:14px;padding:20px}.pom__result ul{columns:2}.pom__actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.pom__actions a{padding:12px 17px;border-radius:8px;text-decoration:none;font-weight:900}.pom__wa{background:#12b76a;color:#fff}.pom__go{background:#f79009;color:#111}@media(max-width:650px){.pom__grid{grid-template-columns:1fr}.pom__result ul{columns:1}}`}</style><div className="pom__w"><h1>Calculadora de Pomar</h1><p>Transforme área disponível em número de mudas, espaçamento e uma prévia de insumos e investimento.</p><div className="pom__grid"><label>Espécie<select value={tipo} onChange={e=>setTipo(e.target.value)}>{Object.entries(ESPECIES).map(([k,v])=><option key={k} value={k}>{v.nome}</option>)}</select></label><label>Comprimento (m)<input type="number" value={comp} onChange={e=>setComp(e.target.value)}/></label><label>Largura (m)<input type="number" value={larg} onChange={e=>setLarg(e.target.value)}/></label></div><section className="pom__result"><h2>Plano inicial</h2><ul><li>Área total: <b>{r.area.toFixed(0)} m²</b></li><li>Área útil: <b>{r.util.toFixed(0)} m²</b></li><li>Espaçamento: <b>{r.e.x} × {r.e.y} m</b></li><li>Mudas: <b>{r.mudas}</b></li>{r.tutores>0&&<li>Tutores: <b>{r.tutores}</b></li>}<li>Adubo orgânico: <b>{r.organico} kg</b></li><li>NPK inicial: <b>{r.npk.toFixed(1)} kg</b></li><li>Mudas estimadas: <b>{brl(r.invest)}</b></li></ul><div className="pom__actions"><a className="pom__wa" href={wa} target="_blank" rel="noreferrer">Montar pedido no WhatsApp</a><Link className="pom__go" to="/mercado-de-plantas">Ver Mercado de Plantas</Link></div></section></div></main>
}
